// Code generated by protoc-gen-go.
// source: github.com/lxr/go.google.musicmanager/internal/upload_proto/data/upload.data.proto
// DO NOT EDIT!

/*
Package google_musicmanager_v0 is a generated protocol buffer package.

It is generated from these files:
	github.com/lxr/go.google.musicmanager/internal/upload_proto/data/upload.data.proto

It has these top-level messages:
	ResponseStatus
	UploadOperation
	ImageUnion
	TrackSample
	ChallengeInfo
	SignedChallengeInfo
	TracksToUpload
	ClientPolicy
	OverrideConfigValue
	OverrideConfigValueCollection
*/
package google_musicmanager_v0

import proto "github.com/golang/protobuf/proto"
import google_musicmanager_v02 "github.com/lxr/go.google.musicmanager/internal/locker_proto/data"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ResponseStatus_ResponseCode int32

const (
	ResponseStatus_UNKNOWN            ResponseStatus_ResponseCode = 0
	ResponseStatus_OK                 ResponseStatus_ResponseCode = 1
	ResponseStatus_ALREADY_EXISTS     ResponseStatus_ResponseCode = 2
	ResponseStatus_SOFT_ERROR         ResponseStatus_ResponseCode = 3
	ResponseStatus_METADATA_TOO_LARGE ResponseStatus_ResponseCode = 4
)

var ResponseStatus_ResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "ALREADY_EXISTS",
	3: "SOFT_ERROR",
	4: "METADATA_TOO_LARGE",
}
var ResponseStatus_ResponseCode_value = map[string]int32{
	"UNKNOWN":            0,
	"OK":                 1,
	"ALREADY_EXISTS":     2,
	"SOFT_ERROR":         3,
	"METADATA_TOO_LARGE": 4,
}

func (x ResponseStatus_ResponseCode) String() string {
	return proto.EnumName(ResponseStatus_ResponseCode_name, int32(x))
}

type UploadOperation_Operation int32

const (
	UploadOperation_OPERATION_NOOP   UploadOperation_Operation = 0
	UploadOperation_OPERATION_CREATE UploadOperation_Operation = 1
	UploadOperation_OPERATION_MODIFY UploadOperation_Operation = 2
	UploadOperation_OPERATION_DELETE UploadOperation_Operation = 3
)

var UploadOperation_Operation_name = map[int32]string{
	0: "OPERATION_NOOP",
	1: "OPERATION_CREATE",
	2: "OPERATION_MODIFY",
	3: "OPERATION_DELETE",
}
var UploadOperation_Operation_value = map[string]int32{
	"OPERATION_NOOP":   0,
	"OPERATION_CREATE": 1,
	"OPERATION_MODIFY": 2,
	"OPERATION_DELETE": 3,
}

func (x UploadOperation_Operation) String() string {
	return proto.EnumName(UploadOperation_Operation_name, int32(x))
}

type TracksToUpload_TrackStatus int32

const (
	TracksToUpload_UNKNOWN          TracksToUpload_TrackStatus = 0
	TracksToUpload_FORCE_REUPLOAD   TracksToUpload_TrackStatus = 3
	TracksToUpload_UPLOAD_REQUESTED TracksToUpload_TrackStatus = 4
)

var TracksToUpload_TrackStatus_name = map[int32]string{
	0: "UNKNOWN",
	3: "FORCE_REUPLOAD",
	4: "UPLOAD_REQUESTED",
}
var TracksToUpload_TrackStatus_value = map[string]int32{
	"UNKNOWN":          0,
	"FORCE_REUPLOAD":   3,
	"UPLOAD_REQUESTED": 4,
}

func (x TracksToUpload_TrackStatus) String() string {
	return proto.EnumName(TracksToUpload_TrackStatus_name, int32(x))
}

type OverrideConfigValue_OverridePriority int32

const (
	OverrideConfigValue_UNKNOWN_PRIORITY        OverrideConfigValue_OverridePriority = 0
	OverrideConfigValue_DEFAULT_PRIORITY        OverrideConfigValue_OverridePriority = -1
	OverrideConfigValue_LOWEST_PRIORITY         OverrideConfigValue_OverridePriority = 100
	OverrideConfigValue_LOW_PRIORITY            OverrideConfigValue_OverridePriority = 200
	OverrideConfigValue_MEDIUM_PRIORITY         OverrideConfigValue_OverridePriority = 300
	OverrideConfigValue_HIGH_PRIORITY           OverrideConfigValue_OverridePriority = 400
	OverrideConfigValue_HIGHEST_PRIORITY        OverrideConfigValue_OverridePriority = 500
	OverrideConfigValue_DEFAULT_SERVER_PRIORITY OverrideConfigValue_OverridePriority = 300
	OverrideConfigValue_DEFAULT_CLIENT_PRIORITY OverrideConfigValue_OverridePriority = 400
)

var OverrideConfigValue_OverridePriority_name = map[int32]string{
	0:   "UNKNOWN_PRIORITY",
	-1:  "DEFAULT_PRIORITY",
	100: "LOWEST_PRIORITY",
	200: "LOW_PRIORITY",
	300: "MEDIUM_PRIORITY",
	400: "HIGH_PRIORITY",
	500: "HIGHEST_PRIORITY",
	// Duplicate value: 300: "DEFAULT_SERVER_PRIORITY",
	// Duplicate value: 400: "DEFAULT_CLIENT_PRIORITY",
}
var OverrideConfigValue_OverridePriority_value = map[string]int32{
	"UNKNOWN_PRIORITY":        0,
	"DEFAULT_PRIORITY":        -1,
	"LOWEST_PRIORITY":         100,
	"LOW_PRIORITY":            200,
	"MEDIUM_PRIORITY":         300,
	"HIGH_PRIORITY":           400,
	"HIGHEST_PRIORITY":        500,
	"DEFAULT_SERVER_PRIORITY": 300,
	"DEFAULT_CLIENT_PRIORITY": 400,
}

func (x OverrideConfigValue_OverridePriority) String() string {
	return proto.EnumName(OverrideConfigValue_OverridePriority_name, int32(x))
}

type ResponseStatus struct {
	ResponseCode ResponseStatus_ResponseCode `protobuf:"varint,1,opt,name=response_code,enum=google.musicmanager.v0.ResponseStatus_ResponseCode" json:"response_code,omitempty"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}

type UploadOperation struct {
	Operation UploadOperation_Operation `protobuf:"varint,1,opt,name=operation,enum=google.musicmanager.v0.UploadOperation_Operation" json:"operation,omitempty"`
}

func (m *UploadOperation) Reset()         { *m = UploadOperation{} }
func (m *UploadOperation) String() string { return proto.CompactTextString(m) }
func (*UploadOperation) ProtoMessage()    {}

type ImageUnion struct {
	UserAlbumArt []byte `protobuf:"bytes,1,opt,name=user_album_art,proto3" json:"user_album_art,omitempty"`
	AlbumArtUrl  string `protobuf:"bytes,2,opt,name=album_art_url" json:"album_art_url,omitempty"`
}

func (m *ImageUnion) Reset()         { *m = ImageUnion{} }
func (m *ImageUnion) String() string { return proto.CompactTextString(m) }
func (*ImageUnion) ProtoMessage()    {}

type TrackSample struct {
	Track               *google_musicmanager_v02.Track            `protobuf:"bytes,1,opt,name=track" json:"track,omitempty"`
	SignedChallengeInfo *SignedChallengeInfo                      `protobuf:"bytes,2,opt,name=signed_challenge_info" json:"signed_challenge_info,omitempty"`
	Sample              []byte                                    `protobuf:"bytes,3,opt,name=sample,proto3" json:"sample,omitempty"`
	SampleFormat        google_musicmanager_v02.Track_ContentType `protobuf:"varint,4,opt,name=sample_format,enum=google.musicmanager.v0.Track_ContentType" json:"sample_format,omitempty"`
	UserAlbumArt        *ImageUnion                               `protobuf:"bytes,5,opt,name=user_album_art" json:"user_album_art,omitempty"`
}

func (m *TrackSample) Reset()         { *m = TrackSample{} }
func (m *TrackSample) String() string { return proto.CompactTextString(m) }
func (*TrackSample) ProtoMessage()    {}

func (m *TrackSample) GetTrack() *google_musicmanager_v02.Track {
	if m != nil {
		return m.Track
	}
	return nil
}

func (m *TrackSample) GetSignedChallengeInfo() *SignedChallengeInfo {
	if m != nil {
		return m.SignedChallengeInfo
	}
	return nil
}

func (m *TrackSample) GetUserAlbumArt() *ImageUnion {
	if m != nil {
		return m.UserAlbumArt
	}
	return nil
}

type ChallengeInfo struct {
	ClientTrackId      string `protobuf:"bytes,1,opt,name=client_track_id" json:"client_track_id,omitempty"`
	StartMillis        int32  `protobuf:"varint,2,opt,name=start_millis" json:"start_millis,omitempty"`
	DurationMillis     int32  `protobuf:"varint,3,opt,name=duration_millis" json:"duration_millis,omitempty"`
	ChallengeUserId    string `protobuf:"bytes,4,opt,name=challenge_user_id" json:"challenge_user_id,omitempty"`
	ChallengeTimestamp int64  `protobuf:"varint,5,opt,name=challenge_timestamp" json:"challenge_timestamp,omitempty"`
	ExpectMatch        bool   `protobuf:"varint,6,opt,name=expect_match" json:"expect_match,omitempty"`
}

func (m *ChallengeInfo) Reset()         { *m = ChallengeInfo{} }
func (m *ChallengeInfo) String() string { return proto.CompactTextString(m) }
func (*ChallengeInfo) ProtoMessage()    {}

type SignedChallengeInfo struct {
	ChallengeInfo *ChallengeInfo `protobuf:"bytes,1,opt,name=challenge_info" json:"challenge_info,omitempty"`
	Signature     []byte         `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SignedChallengeInfo) Reset()         { *m = SignedChallengeInfo{} }
func (m *SignedChallengeInfo) String() string { return proto.CompactTextString(m) }
func (*SignedChallengeInfo) ProtoMessage()    {}

func (m *SignedChallengeInfo) GetChallengeInfo() *ChallengeInfo {
	if m != nil {
		return m.ChallengeInfo
	}
	return nil
}

type TracksToUpload struct {
	ClientId string                     `protobuf:"bytes,1,opt,name=client_id" json:"client_id,omitempty"`
	ServerId string                     `protobuf:"bytes,2,opt,name=server_id" json:"server_id,omitempty"`
	Status   TracksToUpload_TrackStatus `protobuf:"varint,5,opt,name=status,enum=google.musicmanager.v0.TracksToUpload_TrackStatus" json:"status,omitempty"`
}

func (m *TracksToUpload) Reset()         { *m = TracksToUpload{} }
func (m *TracksToUpload) String() string { return proto.CompactTextString(m) }
func (*TracksToUpload) ProtoMessage()    {}

type ClientPolicy struct {
	PauseUploads             bool   `protobuf:"varint,1,opt,name=pause_uploads" json:"pause_uploads,omitempty"`
	Abort                    bool   `protobuf:"varint,2,opt,name=abort" json:"abort,omitempty"`
	RetryInMinutes           int32  `protobuf:"varint,3,opt,name=retry_in_minutes" json:"retry_in_minutes,omitempty"`
	BandwidthCapKbps         int32  `protobuf:"varint,4,opt,name=bandwidth_cap_kbps" json:"bandwidth_cap_kbps,omitempty"`
	PauseDownloads           bool   `protobuf:"varint,5,opt,name=pause_downloads" json:"pause_downloads,omitempty"`
	DownloadBandwidthCapKbps int32  `protobuf:"varint,6,opt,name=download_bandwidth_cap_kbps" json:"download_bandwidth_cap_kbps,omitempty"`
	SendAnalytics            bool   `protobuf:"varint,7,opt,name=send_analytics" json:"send_analytics,omitempty"`
	AnalyticsUrl             string `protobuf:"bytes,8,opt,name=analytics_url" json:"analytics_url,omitempty"`
	EnableGapless            bool   `protobuf:"varint,9,opt,name=enable_gapless" json:"enable_gapless,omitempty"`
	EnableM4P                bool   `protobuf:"varint,10,opt,name=enable_m4p" json:"enable_m4p,omitempty"`
}

func (m *ClientPolicy) Reset()         { *m = ClientPolicy{} }
func (m *ClientPolicy) String() string { return proto.CompactTextString(m) }
func (*ClientPolicy) ProtoMessage()    {}

type OverrideConfigValue struct {
	Key      string                               `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value    string                               `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Priority OverrideConfigValue_OverridePriority `protobuf:"varint,3,opt,name=priority,enum=google.musicmanager.v0.OverrideConfigValue_OverridePriority" json:"priority,omitempty"`
}

func (m *OverrideConfigValue) Reset()         { *m = OverrideConfigValue{} }
func (m *OverrideConfigValue) String() string { return proto.CompactTextString(m) }
func (*OverrideConfigValue) ProtoMessage()    {}

type OverrideConfigValueCollection struct {
	Value []*OverrideConfigValue `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *OverrideConfigValueCollection) Reset()         { *m = OverrideConfigValueCollection{} }
func (m *OverrideConfigValueCollection) String() string { return proto.CompactTextString(m) }
func (*OverrideConfigValueCollection) ProtoMessage()    {}

func (m *OverrideConfigValueCollection) GetValue() []*OverrideConfigValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.musicmanager.v0.ResponseStatus_ResponseCode", ResponseStatus_ResponseCode_name, ResponseStatus_ResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.UploadOperation_Operation", UploadOperation_Operation_name, UploadOperation_Operation_value)
	proto.RegisterEnum("google.musicmanager.v0.TracksToUpload_TrackStatus", TracksToUpload_TrackStatus_name, TracksToUpload_TrackStatus_value)
	proto.RegisterEnum("google.musicmanager.v0.OverrideConfigValue_OverridePriority", OverrideConfigValue_OverridePriority_name, OverrideConfigValue_OverridePriority_value)
}
