// Code generated by protoc-gen-go.
// source: github.com/lxr/go.google.musicmanager/internal/locker_proto/service/locker.messages.proto
// DO NOT EDIT!

/*
Package google_musicmanager_v0 is a generated protocol buffer package.

It is generated from these files:
	github.com/lxr/go.google.musicmanager/internal/locker_proto/service/locker.messages.proto

It has these top-level messages:
	GetTracksRequest
	GetTracksResponse
	GetPlaylistsRequest
	GetPlaylistsResponse
	GetPlaylistEntriesRequest
	GetPlaylistEntriesResponse
	LookupTrackRequest
	LookupPlaylistEntryRequest
	LookupPlaylistRequest
	BatchLookupRequest
	BatchLookupResponse
	MutateTrackRequest
	BatchMutateTracksRequest
	BatchMutateTracksResponse
	MutatePlaylistRequest
	BatchMutatePlaylistsRequest
	BatchMutatePlaylistsResponse
	MutatePlaylistEntryRequest
	BatchMutatePlaylistEntriesRequest
	BatchMutatePlaylistEntriesResponse
	MutateResponse
	MagicPlaylistRequest
	MagicPlaylistResponse
	FlushLockerRequest
	FlushLockerResponse
	GetAlbumsRequest
	GetAlbumsResponse
	GetArtistsRequest
	GetArtistsResponse
	GetGenresRequest
	GetGenresResponse
	GetDynamicPlaylistEntriesRequest
	GetDynamicPlaylistEntriesResponse
	GetAggregationsByTrackTypeRequest
	GetAggregationsByTrackTypeResponse
	GetAggregationsByAvailabilityStatusRequest
	GetAggregationsByAvailabilityStatusResponse
	AddPromoTracksRequest
	AddPromoTracksResponse
	GetPlaylistAggregationsRequest
	GetPlaylistAggregationsResponse
	RemoteControlCommandRequest
	RemoteControlCommandResponse
*/
package google_musicmanager_v0

import proto "github.com/golang/protobuf/proto"
import google_musicmanager_v02 "github.com/lxr/go.google.musicmanager/internal/locker_proto/data"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type GetTracksRequest_TrackProjection int32

const (
	GetTracksRequest_DEFAULT       GetTracksRequest_TrackProjection = 0
	GetTracksRequest_FULL          GetTracksRequest_TrackProjection = 1
	GetTracksRequest_FRONTEND_VIEW GetTracksRequest_TrackProjection = 2
)

var GetTracksRequest_TrackProjection_name = map[int32]string{
	0: "DEFAULT",
	1: "FULL",
	2: "FRONTEND_VIEW",
}
var GetTracksRequest_TrackProjection_value = map[string]int32{
	"DEFAULT":       0,
	"FULL":          1,
	"FRONTEND_VIEW": 2,
}

func (x GetTracksRequest_TrackProjection) String() string {
	return proto.EnumName(GetTracksRequest_TrackProjection_name, int32(x))
}

type GetTracksResponse_ResponseCode int32

const (
	GetTracksResponse_UNKNOWN      GetTracksResponse_ResponseCode = 0
	GetTracksResponse_OK           GetTracksResponse_ResponseCode = 1
	GetTracksResponse_NOT_MODIFIED GetTracksResponse_ResponseCode = 2
	GetTracksResponse_GONE         GetTracksResponse_ResponseCode = 3
)

var GetTracksResponse_ResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "NOT_MODIFIED",
	3: "GONE",
}
var GetTracksResponse_ResponseCode_value = map[string]int32{
	"UNKNOWN":      0,
	"OK":           1,
	"NOT_MODIFIED": 2,
	"GONE":         3,
}

func (x GetTracksResponse_ResponseCode) String() string {
	return proto.EnumName(GetTracksResponse_ResponseCode_name, int32(x))
}

type GetPlaylistsResponse_ResponseCode int32

const (
	GetPlaylistsResponse_UNKNOWN      GetPlaylistsResponse_ResponseCode = 0
	GetPlaylistsResponse_OK           GetPlaylistsResponse_ResponseCode = 1
	GetPlaylistsResponse_NOT_MODIFIED GetPlaylistsResponse_ResponseCode = 2
	GetPlaylistsResponse_GONE         GetPlaylistsResponse_ResponseCode = 3
)

var GetPlaylistsResponse_ResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "NOT_MODIFIED",
	3: "GONE",
}
var GetPlaylistsResponse_ResponseCode_value = map[string]int32{
	"UNKNOWN":      0,
	"OK":           1,
	"NOT_MODIFIED": 2,
	"GONE":         3,
}

func (x GetPlaylistsResponse_ResponseCode) String() string {
	return proto.EnumName(GetPlaylistsResponse_ResponseCode_name, int32(x))
}

type GetPlaylistEntriesResponse_ResponseCode int32

const (
	GetPlaylistEntriesResponse_UNKNOWN      GetPlaylistEntriesResponse_ResponseCode = 0
	GetPlaylistEntriesResponse_OK           GetPlaylistEntriesResponse_ResponseCode = 1
	GetPlaylistEntriesResponse_NOT_MODIFIED GetPlaylistEntriesResponse_ResponseCode = 2
	GetPlaylistEntriesResponse_GONE         GetPlaylistEntriesResponse_ResponseCode = 3
)

var GetPlaylistEntriesResponse_ResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "NOT_MODIFIED",
	3: "GONE",
}
var GetPlaylistEntriesResponse_ResponseCode_value = map[string]int32{
	"UNKNOWN":      0,
	"OK":           1,
	"NOT_MODIFIED": 2,
	"GONE":         3,
}

func (x GetPlaylistEntriesResponse_ResponseCode) String() string {
	return proto.EnumName(GetPlaylistEntriesResponse_ResponseCode_name, int32(x))
}

type BatchLookupRequest_MetadataType int32

const (
	BatchLookupRequest_DEFAULT        BatchLookupRequest_MetadataType = 0
	BatchLookupRequest_TRACK          BatchLookupRequest_MetadataType = 1
	BatchLookupRequest_PLAYLIST       BatchLookupRequest_MetadataType = 2
	BatchLookupRequest_PLAYLIST_ENTRY BatchLookupRequest_MetadataType = 3
)

var BatchLookupRequest_MetadataType_name = map[int32]string{
	0: "DEFAULT",
	1: "TRACK",
	2: "PLAYLIST",
	3: "PLAYLIST_ENTRY",
}
var BatchLookupRequest_MetadataType_value = map[string]int32{
	"DEFAULT":        0,
	"TRACK":          1,
	"PLAYLIST":       2,
	"PLAYLIST_ENTRY": 3,
}

func (x BatchLookupRequest_MetadataType) String() string {
	return proto.EnumName(BatchLookupRequest_MetadataType_name, int32(x))
}

type BatchMutateTracksResponse_BatchMutateTracksResponseCode int32

const (
	BatchMutateTracksResponse_UNKNOWN  BatchMutateTracksResponse_BatchMutateTracksResponseCode = 0
	BatchMutateTracksResponse_OK       BatchMutateTracksResponse_BatchMutateTracksResponseCode = 1
	BatchMutateTracksResponse_CONFLICT BatchMutateTracksResponse_BatchMutateTracksResponseCode = 2
)

var BatchMutateTracksResponse_BatchMutateTracksResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "CONFLICT",
}
var BatchMutateTracksResponse_BatchMutateTracksResponseCode_value = map[string]int32{
	"UNKNOWN":  0,
	"OK":       1,
	"CONFLICT": 2,
}

func (x BatchMutateTracksResponse_BatchMutateTracksResponseCode) String() string {
	return proto.EnumName(BatchMutateTracksResponse_BatchMutateTracksResponseCode_name, int32(x))
}

type BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode int32

const (
	BatchMutatePlaylistsResponse_UNKNOWN  BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode = 0
	BatchMutatePlaylistsResponse_OK       BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode = 1
	BatchMutatePlaylistsResponse_CONFLICT BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode = 2
)

var BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "CONFLICT",
}
var BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode_value = map[string]int32{
	"UNKNOWN":  0,
	"OK":       1,
	"CONFLICT": 2,
}

func (x BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode) String() string {
	return proto.EnumName(BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode_name, int32(x))
}

type BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode int32

const (
	BatchMutatePlaylistEntriesResponse_UNKNOWN  BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode = 0
	BatchMutatePlaylistEntriesResponse_OK       BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode = 1
	BatchMutatePlaylistEntriesResponse_CONFLICT BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode = 2
)

var BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "CONFLICT",
}
var BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode_value = map[string]int32{
	"UNKNOWN":  0,
	"OK":       1,
	"CONFLICT": 2,
}

func (x BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode) String() string {
	return proto.EnumName(BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode_name, int32(x))
}

type MutateResponse_MutateResponseCode int32

const (
	MutateResponse_UNKNOWN            MutateResponse_MutateResponseCode = 0
	MutateResponse_OK                 MutateResponse_MutateResponseCode = 1
	MutateResponse_CONFLICT           MutateResponse_MutateResponseCode = 2
	MutateResponse_INVALID_REQUEST    MutateResponse_MutateResponseCode = 3
	MutateResponse_METADATA_TOO_LARGE MutateResponse_MutateResponseCode = 4
)

var MutateResponse_MutateResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "CONFLICT",
	3: "INVALID_REQUEST",
	4: "METADATA_TOO_LARGE",
}
var MutateResponse_MutateResponseCode_value = map[string]int32{
	"UNKNOWN":            0,
	"OK":                 1,
	"CONFLICT":           2,
	"INVALID_REQUEST":    3,
	"METADATA_TOO_LARGE": 4,
}

func (x MutateResponse_MutateResponseCode) String() string {
	return proto.EnumName(MutateResponse_MutateResponseCode_name, int32(x))
}

type MutateResponse_AvailabilityStatus int32

const (
	MutateResponse_UNKNOWN_AVAILABILITY      MutateResponse_AvailabilityStatus = 0
	MutateResponse_PENDING                   MutateResponse_AvailabilityStatus = 1
	MutateResponse_MATCHED                   MutateResponse_AvailabilityStatus = 2
	MutateResponse_UPLOAD_REQUESTED          MutateResponse_AvailabilityStatus = 3
	MutateResponse_AVAILABLE                 MutateResponse_AvailabilityStatus = 4
	MutateResponse_FORCE_REUPLOAD            MutateResponse_AvailabilityStatus = 5
	MutateResponse_UPLOAD_PERMANENTLY_FAILED MutateResponse_AvailabilityStatus = 6
)

var MutateResponse_AvailabilityStatus_name = map[int32]string{
	0: "UNKNOWN_AVAILABILITY",
	1: "PENDING",
	2: "MATCHED",
	3: "UPLOAD_REQUESTED",
	4: "AVAILABLE",
	5: "FORCE_REUPLOAD",
	6: "UPLOAD_PERMANENTLY_FAILED",
}
var MutateResponse_AvailabilityStatus_value = map[string]int32{
	"UNKNOWN_AVAILABILITY":      0,
	"PENDING":                   1,
	"MATCHED":                   2,
	"UPLOAD_REQUESTED":          3,
	"AVAILABLE":                 4,
	"FORCE_REUPLOAD":            5,
	"UPLOAD_PERMANENTLY_FAILED": 6,
}

func (x MutateResponse_AvailabilityStatus) String() string {
	return proto.EnumName(MutateResponse_AvailabilityStatus_name, int32(x))
}

type GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType int32

const (
	GetDynamicPlaylistEntriesRequest_DEFAULT                GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType = 0
	GetDynamicPlaylistEntriesRequest_PURCHASED              GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType = 1
	GetDynamicPlaylistEntriesRequest_THUMBS_UP              GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType = 2
	GetDynamicPlaylistEntriesRequest_RECENTLY_ADDED         GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType = 3
	GetDynamicPlaylistEntriesRequest_PROMOTED               GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType = 4
	GetDynamicPlaylistEntriesRequest_PROMOTED_AND_PURCHASED GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType = 5
)

var GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType_name = map[int32]string{
	0: "DEFAULT",
	1: "PURCHASED",
	2: "THUMBS_UP",
	3: "RECENTLY_ADDED",
	4: "PROMOTED",
	5: "PROMOTED_AND_PURCHASED",
}
var GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType_value = map[string]int32{
	"DEFAULT":                0,
	"PURCHASED":              1,
	"THUMBS_UP":              2,
	"RECENTLY_ADDED":         3,
	"PROMOTED":               4,
	"PROMOTED_AND_PURCHASED": 5,
}

func (x GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType) String() string {
	return proto.EnumName(GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType_name, int32(x))
}

type GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType int32

const (
	GetDynamicPlaylistEntriesResponse_UNKNOWN_TYPE           GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType = 0
	GetDynamicPlaylistEntriesResponse_PURCHASED              GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType = 1
	GetDynamicPlaylistEntriesResponse_THUMBS_UP              GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType = 2
	GetDynamicPlaylistEntriesResponse_RECENTLY_ADDED         GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType = 3
	GetDynamicPlaylistEntriesResponse_PROMOTED               GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType = 4
	GetDynamicPlaylistEntriesResponse_UNKNOWN                GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType = 5
	GetDynamicPlaylistEntriesResponse_PROMOTED_AND_PURCHASED GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType = 6
)

var GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType_name = map[int32]string{
	0: "UNKNOWN_TYPE",
	1: "PURCHASED",
	2: "THUMBS_UP",
	3: "RECENTLY_ADDED",
	4: "PROMOTED",
	5: "UNKNOWN",
	6: "PROMOTED_AND_PURCHASED",
}
var GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType_value = map[string]int32{
	"UNKNOWN_TYPE":           0,
	"PURCHASED":              1,
	"THUMBS_UP":              2,
	"RECENTLY_ADDED":         3,
	"PROMOTED":               4,
	"UNKNOWN":                5,
	"PROMOTED_AND_PURCHASED": 6,
}

func (x GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType) String() string {
	return proto.EnumName(GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType_name, int32(x))
}

type GetDynamicPlaylistEntriesResponse_ResponseCode int32

const (
	GetDynamicPlaylistEntriesResponse_UNKNOWN_CODE GetDynamicPlaylistEntriesResponse_ResponseCode = 0
	GetDynamicPlaylistEntriesResponse_OK           GetDynamicPlaylistEntriesResponse_ResponseCode = 1
	GetDynamicPlaylistEntriesResponse_NOT_OK       GetDynamicPlaylistEntriesResponse_ResponseCode = 2
)

var GetDynamicPlaylistEntriesResponse_ResponseCode_name = map[int32]string{
	0: "UNKNOWN_CODE",
	1: "OK",
	2: "NOT_OK",
}
var GetDynamicPlaylistEntriesResponse_ResponseCode_value = map[string]int32{
	"UNKNOWN_CODE": 0,
	"OK":           1,
	"NOT_OK":       2,
}

func (x GetDynamicPlaylistEntriesResponse_ResponseCode) String() string {
	return proto.EnumName(GetDynamicPlaylistEntriesResponse_ResponseCode_name, int32(x))
}

type RemoteControlCommandResponse_ResponseCode int32

const (
	RemoteControlCommandResponse_UNKNOWN         RemoteControlCommandResponse_ResponseCode = 0
	RemoteControlCommandResponse_OK              RemoteControlCommandResponse_ResponseCode = 1
	RemoteControlCommandResponse_NO_PUBLISHER    RemoteControlCommandResponse_ResponseCode = 2
	RemoteControlCommandResponse_INVALID_REQUEST RemoteControlCommandResponse_ResponseCode = 3
	RemoteControlCommandResponse_PUBLISH_ERROR   RemoteControlCommandResponse_ResponseCode = 4
)

var RemoteControlCommandResponse_ResponseCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "NO_PUBLISHER",
	3: "INVALID_REQUEST",
	4: "PUBLISH_ERROR",
}
var RemoteControlCommandResponse_ResponseCode_value = map[string]int32{
	"UNKNOWN":         0,
	"OK":              1,
	"NO_PUBLISHER":    2,
	"INVALID_REQUEST": 3,
	"PUBLISH_ERROR":   4,
}

func (x RemoteControlCommandResponse_ResponseCode) String() string {
	return proto.EnumName(RemoteControlCommandResponse_ResponseCode_name, int32(x))
}

type GetTracksRequest struct {
	GaiaId            int64                                              `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	UpdatedMin        int64                                              `protobuf:"varint,2,opt,name=updated_min" json:"updated_min,omitempty"`
	IncludeDeleted    bool                                               `protobuf:"varint,3,opt,name=include_deleted" json:"include_deleted,omitempty"`
	MaxResults        int32                                              `protobuf:"varint,4,opt,name=max_results" json:"max_results,omitempty"`
	ContinuationToken string                                             `protobuf:"bytes,5,opt,name=continuation_token" json:"continuation_token,omitempty"`
	SearchRestriction []*google_musicmanager_v02.TrackSearchRestriction  `protobuf:"bytes,6,rep,name=search_restriction" json:"search_restriction,omitempty"`
	SortOrder         []*google_musicmanager_v02.TrackSortOrder          `protobuf:"bytes,7,rep,name=sort_order" json:"sort_order,omitempty"`
	RestrictionSet    *google_musicmanager_v02.TrackSearchRestrictionSet `protobuf:"bytes,8,opt,name=restriction_set" json:"restriction_set,omitempty"`
	TrackProjection   GetTracksRequest_TrackProjection                   `protobuf:"varint,9,opt,name=track_projection,enum=google.musicmanager.v0.GetTracksRequest_TrackProjection" json:"track_projection,omitempty"`
}

func (m *GetTracksRequest) Reset()         { *m = GetTracksRequest{} }
func (m *GetTracksRequest) String() string { return proto.CompactTextString(m) }
func (*GetTracksRequest) ProtoMessage()    {}

func (m *GetTracksRequest) GetSearchRestriction() []*google_musicmanager_v02.TrackSearchRestriction {
	if m != nil {
		return m.SearchRestriction
	}
	return nil
}

func (m *GetTracksRequest) GetSortOrder() []*google_musicmanager_v02.TrackSortOrder {
	if m != nil {
		return m.SortOrder
	}
	return nil
}

func (m *GetTracksRequest) GetRestrictionSet() *google_musicmanager_v02.TrackSearchRestrictionSet {
	if m != nil {
		return m.RestrictionSet
	}
	return nil
}

type GetTracksResponse struct {
	ResponseCode          GetTracksResponse_ResponseCode   `protobuf:"varint,1,opt,name=response_code,enum=google.musicmanager.v0.GetTracksResponse_ResponseCode" json:"response_code,omitempty"`
	Track                 []*google_musicmanager_v02.Track `protobuf:"bytes,2,rep,name=track" json:"track,omitempty"`
	EstimatedTotalResults int64                            `protobuf:"varint,3,opt,name=estimated_total_results" json:"estimated_total_results,omitempty"`
	ContinuationToken     string                           `protobuf:"bytes,4,opt,name=continuation_token" json:"continuation_token,omitempty"`
}

func (m *GetTracksResponse) Reset()         { *m = GetTracksResponse{} }
func (m *GetTracksResponse) String() string { return proto.CompactTextString(m) }
func (*GetTracksResponse) ProtoMessage()    {}

func (m *GetTracksResponse) GetTrack() []*google_musicmanager_v02.Track {
	if m != nil {
		return m.Track
	}
	return nil
}

type GetPlaylistsRequest struct {
	GaiaId            int64                                      `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	UpdatedMin        int64                                      `protobuf:"varint,2,opt,name=updated_min" json:"updated_min,omitempty"`
	IncludeDeleted    bool                                       `protobuf:"varint,3,opt,name=include_deleted" json:"include_deleted,omitempty"`
	MaxResults        int32                                      `protobuf:"varint,4,opt,name=max_results" json:"max_results,omitempty"`
	ContinuationToken string                                     `protobuf:"bytes,5,opt,name=continuation_token" json:"continuation_token,omitempty"`
	SortOrder         *google_musicmanager_v02.PlaylistSortOrder `protobuf:"bytes,6,opt,name=sort_order" json:"sort_order,omitempty"`
}

func (m *GetPlaylistsRequest) Reset()         { *m = GetPlaylistsRequest{} }
func (m *GetPlaylistsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlaylistsRequest) ProtoMessage()    {}

func (m *GetPlaylistsRequest) GetSortOrder() *google_musicmanager_v02.PlaylistSortOrder {
	if m != nil {
		return m.SortOrder
	}
	return nil
}

type GetPlaylistsResponse struct {
	ResponseCode          GetPlaylistsResponse_ResponseCode   `protobuf:"varint,1,opt,name=response_code,enum=google.musicmanager.v0.GetPlaylistsResponse_ResponseCode" json:"response_code,omitempty"`
	Playlist              []*google_musicmanager_v02.Playlist `protobuf:"bytes,2,rep,name=playlist" json:"playlist,omitempty"`
	EstimatedTotalResults int64                               `protobuf:"varint,3,opt,name=estimated_total_results" json:"estimated_total_results,omitempty"`
	ContinuationToken     string                              `protobuf:"bytes,4,opt,name=continuation_token" json:"continuation_token,omitempty"`
}

func (m *GetPlaylistsResponse) Reset()         { *m = GetPlaylistsResponse{} }
func (m *GetPlaylistsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlaylistsResponse) ProtoMessage()    {}

func (m *GetPlaylistsResponse) GetPlaylist() []*google_musicmanager_v02.Playlist {
	if m != nil {
		return m.Playlist
	}
	return nil
}

type GetPlaylistEntriesRequest struct {
	GaiaId                  int64  `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	UpdatedMin              int64  `protobuf:"varint,2,opt,name=updated_min" json:"updated_min,omitempty"`
	IncludeDeleted          bool   `protobuf:"varint,3,opt,name=include_deleted" json:"include_deleted,omitempty"`
	MaxResults              int32  `protobuf:"varint,4,opt,name=max_results" json:"max_results,omitempty"`
	ContinuationToken       string `protobuf:"bytes,5,opt,name=continuation_token" json:"continuation_token,omitempty"`
	PlaylistIdFilter        string `protobuf:"bytes,6,opt,name=playlist_id_filter" json:"playlist_id_filter,omitempty"`
	IncludeAllTrackMetadata bool   `protobuf:"varint,7,opt,name=include_all_track_metadata" json:"include_all_track_metadata,omitempty"`
	OnlyShowAvailableTracks bool   `protobuf:"varint,8,opt,name=only_show_available_tracks" json:"only_show_available_tracks,omitempty"`
}

func (m *GetPlaylistEntriesRequest) Reset()         { *m = GetPlaylistEntriesRequest{} }
func (m *GetPlaylistEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlaylistEntriesRequest) ProtoMessage()    {}

type GetPlaylistEntriesResponse struct {
	ResponseCode          GetPlaylistEntriesResponse_ResponseCode  `protobuf:"varint,1,opt,name=response_code,enum=google.musicmanager.v0.GetPlaylistEntriesResponse_ResponseCode" json:"response_code,omitempty"`
	PlaylistEntry         []*google_musicmanager_v02.PlaylistEntry `protobuf:"bytes,2,rep,name=playlist_entry" json:"playlist_entry,omitempty"`
	EstimatedTotalResults int64                                    `protobuf:"varint,3,opt,name=estimated_total_results" json:"estimated_total_results,omitempty"`
	ContinuationToken     string                                   `protobuf:"bytes,4,opt,name=continuation_token" json:"continuation_token,omitempty"`
}

func (m *GetPlaylistEntriesResponse) Reset()         { *m = GetPlaylistEntriesResponse{} }
func (m *GetPlaylistEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlaylistEntriesResponse) ProtoMessage()    {}

func (m *GetPlaylistEntriesResponse) GetPlaylistEntry() []*google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.PlaylistEntry
	}
	return nil
}

type LookupTrackRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=client_id" json:"client_id,omitempty"`
}

func (m *LookupTrackRequest) Reset()         { *m = LookupTrackRequest{} }
func (m *LookupTrackRequest) String() string { return proto.CompactTextString(m) }
func (*LookupTrackRequest) ProtoMessage()    {}

type LookupPlaylistEntryRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=client_id" json:"client_id,omitempty"`
}

func (m *LookupPlaylistEntryRequest) Reset()         { *m = LookupPlaylistEntryRequest{} }
func (m *LookupPlaylistEntryRequest) String() string { return proto.CompactTextString(m) }
func (*LookupPlaylistEntryRequest) ProtoMessage()    {}

type LookupPlaylistRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=client_id" json:"client_id,omitempty"`
}

func (m *LookupPlaylistRequest) Reset()         { *m = LookupPlaylistRequest{} }
func (m *LookupPlaylistRequest) String() string { return proto.CompactTextString(m) }
func (*LookupPlaylistRequest) ProtoMessage()    {}

type BatchLookupRequest struct {
	GaiaId         int64                           `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	Track          []*LookupTrackRequest           `protobuf:"bytes,2,rep,name=track" json:"track,omitempty"`
	Playlist       []*LookupPlaylistRequest        `protobuf:"bytes,3,rep,name=playlist" json:"playlist,omitempty"`
	MetadataType   BatchLookupRequest_MetadataType `protobuf:"varint,4,opt,name=metadata_type,enum=google.musicmanager.v0.BatchLookupRequest_MetadataType" json:"metadata_type,omitempty"`
	PlaylistEntry  []*LookupPlaylistEntryRequest   `protobuf:"bytes,5,rep,name=playlist_entry" json:"playlist_entry,omitempty"`
	IncludeDeleted bool                            `protobuf:"varint,6,opt,name=include_deleted" json:"include_deleted,omitempty"`
}

func (m *BatchLookupRequest) Reset()         { *m = BatchLookupRequest{} }
func (m *BatchLookupRequest) String() string { return proto.CompactTextString(m) }
func (*BatchLookupRequest) ProtoMessage()    {}

func (m *BatchLookupRequest) GetTrack() []*LookupTrackRequest {
	if m != nil {
		return m.Track
	}
	return nil
}

func (m *BatchLookupRequest) GetPlaylist() []*LookupPlaylistRequest {
	if m != nil {
		return m.Playlist
	}
	return nil
}

func (m *BatchLookupRequest) GetPlaylistEntry() []*LookupPlaylistEntryRequest {
	if m != nil {
		return m.PlaylistEntry
	}
	return nil
}

type BatchLookupResponse struct {
	Track         []*google_musicmanager_v02.Track         `protobuf:"bytes,1,rep,name=track" json:"track,omitempty"`
	Playlist      []*google_musicmanager_v02.Playlist      `protobuf:"bytes,2,rep,name=playlist" json:"playlist,omitempty"`
	PlaylistEntry []*google_musicmanager_v02.PlaylistEntry `protobuf:"bytes,3,rep,name=playlist_entry" json:"playlist_entry,omitempty"`
}

func (m *BatchLookupResponse) Reset()         { *m = BatchLookupResponse{} }
func (m *BatchLookupResponse) String() string { return proto.CompactTextString(m) }
func (*BatchLookupResponse) ProtoMessage()    {}

func (m *BatchLookupResponse) GetTrack() []*google_musicmanager_v02.Track {
	if m != nil {
		return m.Track
	}
	return nil
}

func (m *BatchLookupResponse) GetPlaylist() []*google_musicmanager_v02.Playlist {
	if m != nil {
		return m.Playlist
	}
	return nil
}

func (m *BatchLookupResponse) GetPlaylistEntry() []*google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.PlaylistEntry
	}
	return nil
}

type MutateTrackRequest struct {
	CreateTrack        *google_musicmanager_v02.Track `protobuf:"bytes,1,opt,name=create_track" json:"create_track,omitempty"`
	UpdateTrack        *google_musicmanager_v02.Track `protobuf:"bytes,2,opt,name=update_track" json:"update_track,omitempty"`
	DeleteTrack        string                         `protobuf:"bytes,3,opt,name=delete_track" json:"delete_track,omitempty"`
	PartialUpdate      bool                           `protobuf:"varint,4,opt,name=partial_update" json:"partial_update,omitempty"`
	UpdateLastModified bool                           `protobuf:"varint,5,opt,name=update_last_modified" json:"update_last_modified,omitempty"`
	UndeleteTrack      string                         `protobuf:"bytes,6,opt,name=undelete_track" json:"undelete_track,omitempty"`
}

func (m *MutateTrackRequest) Reset()         { *m = MutateTrackRequest{} }
func (m *MutateTrackRequest) String() string { return proto.CompactTextString(m) }
func (*MutateTrackRequest) ProtoMessage()    {}

func (m *MutateTrackRequest) GetCreateTrack() *google_musicmanager_v02.Track {
	if m != nil {
		return m.CreateTrack
	}
	return nil
}

func (m *MutateTrackRequest) GetUpdateTrack() *google_musicmanager_v02.Track {
	if m != nil {
		return m.UpdateTrack
	}
	return nil
}

type BatchMutateTracksRequest struct {
	GaiaId                   int64                 `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	TrackMutation            []*MutateTrackRequest `protobuf:"bytes,2,rep,name=track_mutation" json:"track_mutation,omitempty"`
	SendNotification         bool                  `protobuf:"varint,3,opt,name=send_notification" json:"send_notification,omitempty"`
	DetectTimestampConflict  bool                  `protobuf:"varint,4,opt,name=detect_timestamp_conflict" json:"detect_timestamp_conflict,omitempty"`
	NotifyFineGrainedUpdates bool                  `protobuf:"varint,5,opt,name=notify_fine_grained_updates" json:"notify_fine_grained_updates,omitempty"`
}

func (m *BatchMutateTracksRequest) Reset()         { *m = BatchMutateTracksRequest{} }
func (m *BatchMutateTracksRequest) String() string { return proto.CompactTextString(m) }
func (*BatchMutateTracksRequest) ProtoMessage()    {}

func (m *BatchMutateTracksRequest) GetTrackMutation() []*MutateTrackRequest {
	if m != nil {
		return m.TrackMutation
	}
	return nil
}

type BatchMutateTracksResponse struct {
	ResponseCode   []BatchMutateTracksResponse_BatchMutateTracksResponseCode `protobuf:"varint,1,rep,name=response_code,enum=google.musicmanager.v0.BatchMutateTracksResponse_BatchMutateTracksResponseCode" json:"response_code,omitempty"`
	MutateResponse []*MutateResponse                                         `protobuf:"bytes,2,rep,name=mutate_response" json:"mutate_response,omitempty"`
}

func (m *BatchMutateTracksResponse) Reset()         { *m = BatchMutateTracksResponse{} }
func (m *BatchMutateTracksResponse) String() string { return proto.CompactTextString(m) }
func (*BatchMutateTracksResponse) ProtoMessage()    {}

func (m *BatchMutateTracksResponse) GetMutateResponse() []*MutateResponse {
	if m != nil {
		return m.MutateResponse
	}
	return nil
}

type MutatePlaylistRequest struct {
	CreatePlaylist     *google_musicmanager_v02.Playlist        `protobuf:"bytes,1,opt,name=create_playlist" json:"create_playlist,omitempty"`
	UpdatePlaylist     *google_musicmanager_v02.Playlist        `protobuf:"bytes,2,opt,name=update_playlist" json:"update_playlist,omitempty"`
	DeletePlaylist     string                                   `protobuf:"bytes,3,opt,name=delete_playlist" json:"delete_playlist,omitempty"`
	PartialUpdate      bool                                     `protobuf:"varint,4,opt,name=partial_update" json:"partial_update,omitempty"`
	PlaylistEntry      []*google_musicmanager_v02.PlaylistEntry `protobuf:"bytes,5,rep,name=playlist_entry" json:"playlist_entry,omitempty"`
	UpdateLastModified bool                                     `protobuf:"varint,6,opt,name=update_last_modified" json:"update_last_modified,omitempty"`
	UndeletePlaylist   string                                   `protobuf:"bytes,7,opt,name=undelete_playlist" json:"undelete_playlist,omitempty"`
}

func (m *MutatePlaylistRequest) Reset()         { *m = MutatePlaylistRequest{} }
func (m *MutatePlaylistRequest) String() string { return proto.CompactTextString(m) }
func (*MutatePlaylistRequest) ProtoMessage()    {}

func (m *MutatePlaylistRequest) GetCreatePlaylist() *google_musicmanager_v02.Playlist {
	if m != nil {
		return m.CreatePlaylist
	}
	return nil
}

func (m *MutatePlaylistRequest) GetUpdatePlaylist() *google_musicmanager_v02.Playlist {
	if m != nil {
		return m.UpdatePlaylist
	}
	return nil
}

func (m *MutatePlaylistRequest) GetPlaylistEntry() []*google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.PlaylistEntry
	}
	return nil
}

type BatchMutatePlaylistsRequest struct {
	GaiaId                   int64                    `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	PlaylistMutation         []*MutatePlaylistRequest `protobuf:"bytes,2,rep,name=playlist_mutation" json:"playlist_mutation,omitempty"`
	SendNotification         bool                     `protobuf:"varint,3,opt,name=send_notification" json:"send_notification,omitempty"`
	DetectTimestampConflict  bool                     `protobuf:"varint,4,opt,name=detect_timestamp_conflict" json:"detect_timestamp_conflict,omitempty"`
	NotifyFineGrainedUpdates bool                     `protobuf:"varint,5,opt,name=notify_fine_grained_updates" json:"notify_fine_grained_updates,omitempty"`
}

func (m *BatchMutatePlaylistsRequest) Reset()         { *m = BatchMutatePlaylistsRequest{} }
func (m *BatchMutatePlaylistsRequest) String() string { return proto.CompactTextString(m) }
func (*BatchMutatePlaylistsRequest) ProtoMessage()    {}

func (m *BatchMutatePlaylistsRequest) GetPlaylistMutation() []*MutatePlaylistRequest {
	if m != nil {
		return m.PlaylistMutation
	}
	return nil
}

type BatchMutatePlaylistsResponse struct {
	ResponseCode   []BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode `protobuf:"varint,1,rep,name=response_code,enum=google.musicmanager.v0.BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode" json:"response_code,omitempty"`
	MutateResponse []*MutateResponse                                               `protobuf:"bytes,2,rep,name=mutate_response" json:"mutate_response,omitempty"`
}

func (m *BatchMutatePlaylistsResponse) Reset()         { *m = BatchMutatePlaylistsResponse{} }
func (m *BatchMutatePlaylistsResponse) String() string { return proto.CompactTextString(m) }
func (*BatchMutatePlaylistsResponse) ProtoMessage()    {}

func (m *BatchMutatePlaylistsResponse) GetMutateResponse() []*MutateResponse {
	if m != nil {
		return m.MutateResponse
	}
	return nil
}

type MutatePlaylistEntryRequest struct {
	CreatePlaylistEntry   *google_musicmanager_v02.PlaylistEntry `protobuf:"bytes,1,opt,name=create_playlist_entry" json:"create_playlist_entry,omitempty"`
	UpdatePlaylistEntry   *google_musicmanager_v02.PlaylistEntry `protobuf:"bytes,2,opt,name=update_playlist_entry" json:"update_playlist_entry,omitempty"`
	DeletePlaylistEntry   *google_musicmanager_v02.PlaylistEntry `protobuf:"bytes,3,opt,name=delete_playlist_entry" json:"delete_playlist_entry,omitempty"`
	UpdateLastModified    bool                                   `protobuf:"varint,4,opt,name=update_last_modified" json:"update_last_modified,omitempty"`
	UndeletePlaylistEntry string                                 `protobuf:"bytes,5,opt,name=undelete_playlist_entry" json:"undelete_playlist_entry,omitempty"`
}

func (m *MutatePlaylistEntryRequest) Reset()         { *m = MutatePlaylistEntryRequest{} }
func (m *MutatePlaylistEntryRequest) String() string { return proto.CompactTextString(m) }
func (*MutatePlaylistEntryRequest) ProtoMessage()    {}

func (m *MutatePlaylistEntryRequest) GetCreatePlaylistEntry() *google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.CreatePlaylistEntry
	}
	return nil
}

func (m *MutatePlaylistEntryRequest) GetUpdatePlaylistEntry() *google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.UpdatePlaylistEntry
	}
	return nil
}

func (m *MutatePlaylistEntryRequest) GetDeletePlaylistEntry() *google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.DeletePlaylistEntry
	}
	return nil
}

type BatchMutatePlaylistEntriesRequest struct {
	GaiaId                   int64                         `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	PlaylistEntryMutation    []*MutatePlaylistEntryRequest `protobuf:"bytes,2,rep,name=playlist_entry_mutation" json:"playlist_entry_mutation,omitempty"`
	SendNotification         bool                          `protobuf:"varint,3,opt,name=send_notification" json:"send_notification,omitempty"`
	DetectTimestampConflict  bool                          `protobuf:"varint,4,opt,name=detect_timestamp_conflict" json:"detect_timestamp_conflict,omitempty"`
	NotifyFineGrainedUpdates bool                          `protobuf:"varint,5,opt,name=notify_fine_grained_updates" json:"notify_fine_grained_updates,omitempty"`
}

func (m *BatchMutatePlaylistEntriesRequest) Reset()         { *m = BatchMutatePlaylistEntriesRequest{} }
func (m *BatchMutatePlaylistEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*BatchMutatePlaylistEntriesRequest) ProtoMessage()    {}

func (m *BatchMutatePlaylistEntriesRequest) GetPlaylistEntryMutation() []*MutatePlaylistEntryRequest {
	if m != nil {
		return m.PlaylistEntryMutation
	}
	return nil
}

type BatchMutatePlaylistEntriesResponse struct {
	ResponseCode   []BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode `protobuf:"varint,1,rep,name=response_code,enum=google.musicmanager.v0.BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode" json:"response_code,omitempty"`
	MutateResponse []*MutateResponse                                                           `protobuf:"bytes,2,rep,name=mutate_response" json:"mutate_response,omitempty"`
}

func (m *BatchMutatePlaylistEntriesResponse) Reset()         { *m = BatchMutatePlaylistEntriesResponse{} }
func (m *BatchMutatePlaylistEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*BatchMutatePlaylistEntriesResponse) ProtoMessage()    {}

func (m *BatchMutatePlaylistEntriesResponse) GetMutateResponse() []*MutateResponse {
	if m != nil {
		return m.MutateResponse
	}
	return nil
}

type MutateResponse struct {
	ResponseCode       MutateResponse_MutateResponseCode `protobuf:"varint,1,opt,name=response_code,enum=google.musicmanager.v0.MutateResponse_MutateResponseCode" json:"response_code,omitempty"`
	Id                 string                            `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ChildId            []string                          `protobuf:"bytes,3,rep,name=child_id" json:"child_id,omitempty"`
	ClientId           string                            `protobuf:"bytes,4,opt,name=client_id" json:"client_id,omitempty"`
	AvailabilityStatus MutateResponse_AvailabilityStatus `protobuf:"varint,5,opt,name=availability_status,enum=google.musicmanager.v0.MutateResponse_AvailabilityStatus" json:"availability_status,omitempty"`
	ErrorMessage       string                            `protobuf:"bytes,6,opt,name=error_message" json:"error_message,omitempty"`
}

func (m *MutateResponse) Reset()         { *m = MutateResponse{} }
func (m *MutateResponse) String() string { return proto.CompactTextString(m) }
func (*MutateResponse) ProtoMessage()    {}

type MagicPlaylistRequest struct {
	GaiaId                  int64                                        `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	PlaylistName            string                                       `protobuf:"bytes,2,opt,name=playlist_name" json:"playlist_name,omitempty"`
	PlaylistId              string                                       `protobuf:"bytes,3,opt,name=playlist_id" json:"playlist_id,omitempty"`
	Seed                    []*google_musicmanager_v02.MagicPlaylistSeed `protobuf:"bytes,4,rep,name=seed" json:"seed,omitempty"`
	NumRecommendations      int32                                        `protobuf:"varint,5,opt,name=num_recommendations" json:"num_recommendations,omitempty"`
	IncludeAllTrackMetadata bool                                         `protobuf:"varint,6,opt,name=include_all_track_metadata" json:"include_all_track_metadata,omitempty"`
	ModelName               string                                       `protobuf:"bytes,7,opt,name=model_name" json:"model_name,omitempty"`
}

func (m *MagicPlaylistRequest) Reset()         { *m = MagicPlaylistRequest{} }
func (m *MagicPlaylistRequest) String() string { return proto.CompactTextString(m) }
func (*MagicPlaylistRequest) ProtoMessage()    {}

func (m *MagicPlaylistRequest) GetSeed() []*google_musicmanager_v02.MagicPlaylistSeed {
	if m != nil {
		return m.Seed
	}
	return nil
}

type MagicPlaylistResponse struct {
	Playlist      *google_musicmanager_v02.Playlist        `protobuf:"bytes,1,opt,name=playlist" json:"playlist,omitempty"`
	PlaylistEntry []*google_musicmanager_v02.PlaylistEntry `protobuf:"bytes,2,rep,name=playlist_entry" json:"playlist_entry,omitempty"`
}

func (m *MagicPlaylistResponse) Reset()         { *m = MagicPlaylistResponse{} }
func (m *MagicPlaylistResponse) String() string { return proto.CompactTextString(m) }
func (*MagicPlaylistResponse) ProtoMessage()    {}

func (m *MagicPlaylistResponse) GetPlaylist() *google_musicmanager_v02.Playlist {
	if m != nil {
		return m.Playlist
	}
	return nil
}

func (m *MagicPlaylistResponse) GetPlaylistEntry() []*google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.PlaylistEntry
	}
	return nil
}

type FlushLockerRequest struct {
	GaiaId                   int64  `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	GaiaCookie               string `protobuf:"bytes,2,opt,name=gaia_cookie" json:"gaia_cookie,omitempty"`
	RemoveAudioBinaries      bool   `protobuf:"varint,3,opt,name=remove_audio_binaries" json:"remove_audio_binaries,omitempty"`
	RemoveImageBinaries      bool   `protobuf:"varint,4,opt,name=remove_image_binaries" json:"remove_image_binaries,omitempty"`
	SendNotification         bool   `protobuf:"varint,5,opt,name=send_notification" json:"send_notification,omitempty"`
	ResetSubscriptionType    bool   `protobuf:"varint,6,opt,name=reset_subscription_type" json:"reset_subscription_type,omitempty"`
	NotifyFineGrainedUpdates bool   `protobuf:"varint,8,opt,name=notify_fine_grained_updates" json:"notify_fine_grained_updates,omitempty"`
}

func (m *FlushLockerRequest) Reset()         { *m = FlushLockerRequest{} }
func (m *FlushLockerRequest) String() string { return proto.CompactTextString(m) }
func (*FlushLockerRequest) ProtoMessage()    {}

type FlushLockerResponse struct {
	TracksRemoved                int32 `protobuf:"varint,1,opt,name=tracks_removed" json:"tracks_removed,omitempty"`
	EntriesRemoved               int32 `protobuf:"varint,2,opt,name=entries_removed" json:"entries_removed,omitempty"`
	PlaylistsRemoved             int32 `protobuf:"varint,3,opt,name=playlists_removed" json:"playlists_removed,omitempty"`
	SuccessResetSubscriptionType bool  `protobuf:"varint,4,opt,name=success_reset_subscription_type" json:"success_reset_subscription_type,omitempty"`
}

func (m *FlushLockerResponse) Reset()         { *m = FlushLockerResponse{} }
func (m *FlushLockerResponse) String() string { return proto.CompactTextString(m) }
func (*FlushLockerResponse) ProtoMessage()    {}

type GetAlbumsRequest struct {
	GaiaId     int64                                   `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	SortOrder  *google_musicmanager_v02.AlbumSortOrder `protobuf:"bytes,2,opt,name=sort_order" json:"sort_order,omitempty"`
	MaxResults int32                                   `protobuf:"varint,3,opt,name=max_results" json:"max_results,omitempty"`
}

func (m *GetAlbumsRequest) Reset()         { *m = GetAlbumsRequest{} }
func (m *GetAlbumsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlbumsRequest) ProtoMessage()    {}

func (m *GetAlbumsRequest) GetSortOrder() *google_musicmanager_v02.AlbumSortOrder {
	if m != nil {
		return m.SortOrder
	}
	return nil
}

type GetAlbumsResponse struct {
	Album []*google_musicmanager_v02.Album `protobuf:"bytes,1,rep,name=album" json:"album,omitempty"`
}

func (m *GetAlbumsResponse) Reset()         { *m = GetAlbumsResponse{} }
func (m *GetAlbumsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAlbumsResponse) ProtoMessage()    {}

func (m *GetAlbumsResponse) GetAlbum() []*google_musicmanager_v02.Album {
	if m != nil {
		return m.Album
	}
	return nil
}

type GetArtistsRequest struct {
	GaiaId     int64                                    `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	SortOrder  *google_musicmanager_v02.ArtistSortOrder `protobuf:"bytes,2,opt,name=sort_order" json:"sort_order,omitempty"`
	MaxResults int32                                    `protobuf:"varint,3,opt,name=max_results" json:"max_results,omitempty"`
}

func (m *GetArtistsRequest) Reset()         { *m = GetArtistsRequest{} }
func (m *GetArtistsRequest) String() string { return proto.CompactTextString(m) }
func (*GetArtistsRequest) ProtoMessage()    {}

func (m *GetArtistsRequest) GetSortOrder() *google_musicmanager_v02.ArtistSortOrder {
	if m != nil {
		return m.SortOrder
	}
	return nil
}

type GetArtistsResponse struct {
	Artist []*google_musicmanager_v02.Artist `protobuf:"bytes,1,rep,name=artist" json:"artist,omitempty"`
}

func (m *GetArtistsResponse) Reset()         { *m = GetArtistsResponse{} }
func (m *GetArtistsResponse) String() string { return proto.CompactTextString(m) }
func (*GetArtistsResponse) ProtoMessage()    {}

func (m *GetArtistsResponse) GetArtist() []*google_musicmanager_v02.Artist {
	if m != nil {
		return m.Artist
	}
	return nil
}

type GetGenresRequest struct {
	GaiaId     int64                                   `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	SortOrder  *google_musicmanager_v02.GenreSortOrder `protobuf:"bytes,2,opt,name=sort_order" json:"sort_order,omitempty"`
	MaxResults int32                                   `protobuf:"varint,3,opt,name=max_results" json:"max_results,omitempty"`
}

func (m *GetGenresRequest) Reset()         { *m = GetGenresRequest{} }
func (m *GetGenresRequest) String() string { return proto.CompactTextString(m) }
func (*GetGenresRequest) ProtoMessage()    {}

func (m *GetGenresRequest) GetSortOrder() *google_musicmanager_v02.GenreSortOrder {
	if m != nil {
		return m.SortOrder
	}
	return nil
}

type GetGenresResponse struct {
	Genre []*google_musicmanager_v02.Genre `protobuf:"bytes,1,rep,name=genre" json:"genre,omitempty"`
}

func (m *GetGenresResponse) Reset()         { *m = GetGenresResponse{} }
func (m *GetGenresResponse) String() string { return proto.CompactTextString(m) }
func (*GetGenresResponse) ProtoMessage()    {}

func (m *GetGenresResponse) GetGenre() []*google_musicmanager_v02.Genre {
	if m != nil {
		return m.Genre
	}
	return nil
}

type GetDynamicPlaylistEntriesRequest struct {
	GaiaId                  int64                                                       `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	PlaylistEntriesType     GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType `protobuf:"varint,4,opt,name=playlist_entries_type,enum=google.musicmanager.v0.GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType" json:"playlist_entries_type,omitempty"`
	MaxResults              int32                                                       `protobuf:"varint,2,opt,name=max_results" json:"max_results,omitempty"`
	ContinuationToken       string                                                      `protobuf:"bytes,3,opt,name=continuation_token" json:"continuation_token,omitempty"`
	IncludeAllTrackMetadata bool                                                        `protobuf:"varint,5,opt,name=include_all_track_metadata" json:"include_all_track_metadata,omitempty"`
}

func (m *GetDynamicPlaylistEntriesRequest) Reset()         { *m = GetDynamicPlaylistEntriesRequest{} }
func (m *GetDynamicPlaylistEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDynamicPlaylistEntriesRequest) ProtoMessage()    {}

type GetDynamicPlaylistEntriesResponse struct {
	ResponseCode          GetDynamicPlaylistEntriesResponse_ResponseCode               `protobuf:"varint,1,opt,name=response_code,enum=google.musicmanager.v0.GetDynamicPlaylistEntriesResponse_ResponseCode" json:"response_code,omitempty"`
	PlaylistEntry         []*google_musicmanager_v02.PlaylistEntry                     `protobuf:"bytes,2,rep,name=playlist_entry" json:"playlist_entry,omitempty"`
	EstimatedTotalResults int64                                                        `protobuf:"varint,3,opt,name=estimated_total_results" json:"estimated_total_results,omitempty"`
	ContinuationToken     string                                                       `protobuf:"bytes,4,opt,name=continuation_token" json:"continuation_token,omitempty"`
	PlaylistEntriesType   GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType `protobuf:"varint,5,opt,name=playlist_entries_type,enum=google.musicmanager.v0.GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType" json:"playlist_entries_type,omitempty"`
}

func (m *GetDynamicPlaylistEntriesResponse) Reset()         { *m = GetDynamicPlaylistEntriesResponse{} }
func (m *GetDynamicPlaylistEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDynamicPlaylistEntriesResponse) ProtoMessage()    {}

func (m *GetDynamicPlaylistEntriesResponse) GetPlaylistEntry() []*google_musicmanager_v02.PlaylistEntry {
	if m != nil {
		return m.PlaylistEntry
	}
	return nil
}

type GetAggregationsByTrackTypeRequest struct {
	GaiaId int64 `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
}

func (m *GetAggregationsByTrackTypeRequest) Reset()         { *m = GetAggregationsByTrackTypeRequest{} }
func (m *GetAggregationsByTrackTypeRequest) String() string { return proto.CompactTextString(m) }
func (*GetAggregationsByTrackTypeRequest) ProtoMessage()    {}

type GetAggregationsByTrackTypeResponse struct {
	TrackTypeAggregate []*google_musicmanager_v02.TrackTypeAggregate `protobuf:"bytes,1,rep,name=track_type_aggregate" json:"track_type_aggregate,omitempty"`
}

func (m *GetAggregationsByTrackTypeResponse) Reset()         { *m = GetAggregationsByTrackTypeResponse{} }
func (m *GetAggregationsByTrackTypeResponse) String() string { return proto.CompactTextString(m) }
func (*GetAggregationsByTrackTypeResponse) ProtoMessage()    {}

func (m *GetAggregationsByTrackTypeResponse) GetTrackTypeAggregate() []*google_musicmanager_v02.TrackTypeAggregate {
	if m != nil {
		return m.TrackTypeAggregate
	}
	return nil
}

type GetAggregationsByAvailabilityStatusRequest struct {
	GaiaId int64 `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
}

func (m *GetAggregationsByAvailabilityStatusRequest) Reset() {
	*m = GetAggregationsByAvailabilityStatusRequest{}
}
func (m *GetAggregationsByAvailabilityStatusRequest) String() string {
	return proto.CompactTextString(m)
}
func (*GetAggregationsByAvailabilityStatusRequest) ProtoMessage() {}

type GetAggregationsByAvailabilityStatusResponse struct {
	AvailabilityStatusAggregate []*google_musicmanager_v02.AvailabilityStatusAggregate `protobuf:"bytes,1,rep,name=availability_status_aggregate" json:"availability_status_aggregate,omitempty"`
}

func (m *GetAggregationsByAvailabilityStatusResponse) Reset() {
	*m = GetAggregationsByAvailabilityStatusResponse{}
}
func (m *GetAggregationsByAvailabilityStatusResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetAggregationsByAvailabilityStatusResponse) ProtoMessage() {}

func (m *GetAggregationsByAvailabilityStatusResponse) GetAvailabilityStatusAggregate() []*google_musicmanager_v02.AvailabilityStatusAggregate {
	if m != nil {
		return m.AvailabilityStatusAggregate
	}
	return nil
}

type AddPromoTracksRequest struct {
	GaiaId int64    `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	Genre  []string `protobuf:"bytes,2,rep,name=genre" json:"genre,omitempty"`
}

func (m *AddPromoTracksRequest) Reset()         { *m = AddPromoTracksRequest{} }
func (m *AddPromoTracksRequest) String() string { return proto.CompactTextString(m) }
func (*AddPromoTracksRequest) ProtoMessage()    {}

type AddPromoTracksResponse struct {
	Track []*google_musicmanager_v02.Track `protobuf:"bytes,1,rep,name=track" json:"track,omitempty"`
}

func (m *AddPromoTracksResponse) Reset()         { *m = AddPromoTracksResponse{} }
func (m *AddPromoTracksResponse) String() string { return proto.CompactTextString(m) }
func (*AddPromoTracksResponse) ProtoMessage()    {}

func (m *AddPromoTracksResponse) GetTrack() []*google_musicmanager_v02.Track {
	if m != nil {
		return m.Track
	}
	return nil
}

type GetPlaylistAggregationsRequest struct {
	GaiaId     int64 `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	MaxResults int32 `protobuf:"varint,2,opt,name=max_results" json:"max_results,omitempty"`
}

func (m *GetPlaylistAggregationsRequest) Reset()         { *m = GetPlaylistAggregationsRequest{} }
func (m *GetPlaylistAggregationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlaylistAggregationsRequest) ProtoMessage()    {}

type GetPlaylistAggregationsResponse struct {
	PlaylistAggregate []*google_musicmanager_v02.PlaylistAggregate `protobuf:"bytes,1,rep,name=playlist_aggregate" json:"playlist_aggregate,omitempty"`
}

func (m *GetPlaylistAggregationsResponse) Reset()         { *m = GetPlaylistAggregationsResponse{} }
func (m *GetPlaylistAggregationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlaylistAggregationsResponse) ProtoMessage()    {}

func (m *GetPlaylistAggregationsResponse) GetPlaylistAggregate() []*google_musicmanager_v02.PlaylistAggregate {
	if m != nil {
		return m.PlaylistAggregate
	}
	return nil
}

type RemoteControlCommandRequest struct {
	GaiaId  int64  `protobuf:"varint,1,opt,name=gaia_id" json:"gaia_id,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *RemoteControlCommandRequest) Reset()         { *m = RemoteControlCommandRequest{} }
func (m *RemoteControlCommandRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteControlCommandRequest) ProtoMessage()    {}

type RemoteControlCommandResponse struct {
	ResponseCode RemoteControlCommandResponse_ResponseCode `protobuf:"varint,1,opt,name=response_code,enum=google.musicmanager.v0.RemoteControlCommandResponse_ResponseCode" json:"response_code,omitempty"`
}

func (m *RemoteControlCommandResponse) Reset()         { *m = RemoteControlCommandResponse{} }
func (m *RemoteControlCommandResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteControlCommandResponse) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("google.musicmanager.v0.GetTracksRequest_TrackProjection", GetTracksRequest_TrackProjection_name, GetTracksRequest_TrackProjection_value)
	proto.RegisterEnum("google.musicmanager.v0.GetTracksResponse_ResponseCode", GetTracksResponse_ResponseCode_name, GetTracksResponse_ResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.GetPlaylistsResponse_ResponseCode", GetPlaylistsResponse_ResponseCode_name, GetPlaylistsResponse_ResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.GetPlaylistEntriesResponse_ResponseCode", GetPlaylistEntriesResponse_ResponseCode_name, GetPlaylistEntriesResponse_ResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.BatchLookupRequest_MetadataType", BatchLookupRequest_MetadataType_name, BatchLookupRequest_MetadataType_value)
	proto.RegisterEnum("google.musicmanager.v0.BatchMutateTracksResponse_BatchMutateTracksResponseCode", BatchMutateTracksResponse_BatchMutateTracksResponseCode_name, BatchMutateTracksResponse_BatchMutateTracksResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode", BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode_name, BatchMutatePlaylistsResponse_BatchMutatePlaylistsResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode", BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode_name, BatchMutatePlaylistEntriesResponse_BatchMutatePlaylistEntriesResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.MutateResponse_MutateResponseCode", MutateResponse_MutateResponseCode_name, MutateResponse_MutateResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.MutateResponse_AvailabilityStatus", MutateResponse_AvailabilityStatus_name, MutateResponse_AvailabilityStatus_value)
	proto.RegisterEnum("google.musicmanager.v0.GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType", GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType_name, GetDynamicPlaylistEntriesRequest_DynamicPlaylistEntriesType_value)
	proto.RegisterEnum("google.musicmanager.v0.GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType", GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType_name, GetDynamicPlaylistEntriesResponse_DynamicPlaylistEntriesType_value)
	proto.RegisterEnum("google.musicmanager.v0.GetDynamicPlaylistEntriesResponse_ResponseCode", GetDynamicPlaylistEntriesResponse_ResponseCode_name, GetDynamicPlaylistEntriesResponse_ResponseCode_value)
	proto.RegisterEnum("google.musicmanager.v0.RemoteControlCommandResponse_ResponseCode", RemoteControlCommandResponse_ResponseCode_name, RemoteControlCommandResponse_ResponseCode_value)
}
