// Code generated by protoc-gen-go.
// source: github.com/lxr/go.google.musicmanager/internal/download_proto/data/download.data.proto
// DO NOT EDIT!

/*
Package google_musicmanager_v0 is a generated protocol buffer package.

It is generated from these files:
	github.com/lxr/go.google.musicmanager/internal/download_proto/data/download.data.proto

It has these top-level messages:
	DownloadTrackInfo
*/
package google_musicmanager_v0

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type DownloadTrackInfo struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Album       string `protobuf:"bytes,3,opt,name=album" json:"album,omitempty"`
	AlbumArtist string `protobuf:"bytes,4,opt,name=album_artist" json:"album_artist,omitempty"`
	Artist      string `protobuf:"bytes,5,opt,name=artist" json:"artist,omitempty"`
	TrackNumber int32  `protobuf:"varint,6,opt,name=track_number" json:"track_number,omitempty"`
	TrackSize   int64  `protobuf:"varint,7,opt,name=track_size" json:"track_size,omitempty"`
}

func (m *DownloadTrackInfo) Reset()         { *m = DownloadTrackInfo{} }
func (m *DownloadTrackInfo) String() string { return proto.CompactTextString(m) }
func (*DownloadTrackInfo) ProtoMessage()    {}
