// Code generated by protoc-gen-go.
// source: uits.proto
// DO NOT EDIT!

package musicmanager

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProductId_Type int32

const (
	ProductId_UPC  ProductId_Type = 1
	ProductId_GRID ProductId_Type = 2
)

var ProductId_Type_name = map[int32]string{
	1: "UPC",
	2: "GRID",
}
var ProductId_Type_value = map[string]int32{
	"UPC":  1,
	"GRID": 2,
}

func (x ProductId_Type) Enum() *ProductId_Type {
	p := new(ProductId_Type)
	*p = x
	return p
}
func (x ProductId_Type) String() string {
	return proto.EnumName(ProductId_Type_name, int32(x))
}
func (x *ProductId_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProductId_Type_value, data, "ProductId_Type")
	if err != nil {
		return err
	}
	*x = ProductId_Type(value)
	return nil
}

type AssetId_Type int32

const (
	AssetId_ISRC AssetId_Type = 1
)

var AssetId_Type_name = map[int32]string{
	1: "ISRC",
}
var AssetId_Type_value = map[string]int32{
	"ISRC": 1,
}

func (x AssetId_Type) Enum() *AssetId_Type {
	p := new(AssetId_Type)
	*p = x
	return p
}
func (x AssetId_Type) String() string {
	return proto.EnumName(AssetId_Type_name, int32(x))
}
func (x *AssetId_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AssetId_Type_value, data, "AssetId_Type")
	if err != nil {
		return err
	}
	*x = AssetId_Type(value)
	return nil
}

type MediaId_AlgorithmType int32

const (
	MediaId_SHA256 MediaId_AlgorithmType = 1
)

var MediaId_AlgorithmType_name = map[int32]string{
	1: "SHA256",
}
var MediaId_AlgorithmType_value = map[string]int32{
	"SHA256": 1,
}

func (x MediaId_AlgorithmType) Enum() *MediaId_AlgorithmType {
	p := new(MediaId_AlgorithmType)
	*p = x
	return p
}
func (x MediaId_AlgorithmType) String() string {
	return proto.EnumName(MediaId_AlgorithmType_name, int32(x))
}
func (x *MediaId_AlgorithmType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MediaId_AlgorithmType_value, data, "MediaId_AlgorithmType")
	if err != nil {
		return err
	}
	*x = MediaId_AlgorithmType(value)
	return nil
}

type UrlInfo_Type int32

const (
	UrlInfo_WCOM UrlInfo_Type = 1
	UrlInfo_WCOP UrlInfo_Type = 2
	UrlInfo_WOAF UrlInfo_Type = 3
	UrlInfo_WOAR UrlInfo_Type = 4
	UrlInfo_WOAS UrlInfo_Type = 5
	UrlInfo_WORS UrlInfo_Type = 6
	UrlInfo_WPAY UrlInfo_Type = 7
	UrlInfo_WPUB UrlInfo_Type = 8
)

var UrlInfo_Type_name = map[int32]string{
	1: "WCOM",
	2: "WCOP",
	3: "WOAF",
	4: "WOAR",
	5: "WOAS",
	6: "WORS",
	7: "WPAY",
	8: "WPUB",
}
var UrlInfo_Type_value = map[string]int32{
	"WCOM": 1,
	"WCOP": 2,
	"WOAF": 3,
	"WOAR": 4,
	"WOAS": 5,
	"WORS": 6,
	"WPAY": 7,
	"WPUB": 8,
}

func (x UrlInfo_Type) Enum() *UrlInfo_Type {
	p := new(UrlInfo_Type)
	*p = x
	return p
}
func (x UrlInfo_Type) String() string {
	return proto.EnumName(UrlInfo_Type_name, int32(x))
}
func (x *UrlInfo_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UrlInfo_Type_value, data, "UrlInfo_Type")
	if err != nil {
		return err
	}
	*x = UrlInfo_Type(value)
	return nil
}

type CopyrightStatus_Type int32

const (
	CopyrightStatus_UNSPECIFIED       CopyrightStatus_Type = 1
	CopyrightStatus_ALLRIGHTSRESERVED CopyrightStatus_Type = 2
	CopyrightStatus_PRERELEASE        CopyrightStatus_Type = 3
	CopyrightStatus_OTHER             CopyrightStatus_Type = 4
)

var CopyrightStatus_Type_name = map[int32]string{
	1: "UNSPECIFIED",
	2: "ALLRIGHTSRESERVED",
	3: "PRERELEASE",
	4: "OTHER",
}
var CopyrightStatus_Type_value = map[string]int32{
	"UNSPECIFIED":       1,
	"ALLRIGHTSRESERVED": 2,
	"PRERELEASE":        3,
	"OTHER":             4,
}

func (x CopyrightStatus_Type) Enum() *CopyrightStatus_Type {
	p := new(CopyrightStatus_Type)
	*p = x
	return p
}
func (x CopyrightStatus_Type) String() string {
	return proto.EnumName(CopyrightStatus_Type_name, int32(x))
}
func (x *CopyrightStatus_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CopyrightStatus_Type_value, data, "CopyrightStatus_Type")
	if err != nil {
		return err
	}
	*x = CopyrightStatus_Type(value)
	return nil
}

type UitsMetadata_ParentalAdvisoryType int32

const (
	UitsMetadata_UNSPECIFIED UitsMetadata_ParentalAdvisoryType = 1
	UitsMetadata_EXPLICIT    UitsMetadata_ParentalAdvisoryType = 2
	UitsMetadata_EDITED      UitsMetadata_ParentalAdvisoryType = 3
)

var UitsMetadata_ParentalAdvisoryType_name = map[int32]string{
	1: "UNSPECIFIED",
	2: "EXPLICIT",
	3: "EDITED",
}
var UitsMetadata_ParentalAdvisoryType_value = map[string]int32{
	"UNSPECIFIED": 1,
	"EXPLICIT":    2,
	"EDITED":      3,
}

func (x UitsMetadata_ParentalAdvisoryType) Enum() *UitsMetadata_ParentalAdvisoryType {
	p := new(UitsMetadata_ParentalAdvisoryType)
	*p = x
	return p
}
func (x UitsMetadata_ParentalAdvisoryType) String() string {
	return proto.EnumName(UitsMetadata_ParentalAdvisoryType_name, int32(x))
}
func (x *UitsMetadata_ParentalAdvisoryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UitsMetadata_ParentalAdvisoryType_value, data, "UitsMetadata_ParentalAdvisoryType")
	if err != nil {
		return err
	}
	*x = UitsMetadata_ParentalAdvisoryType(value)
	return nil
}

type UitsSignature_AlgorithmType int32

const (
	UitsSignature_RSA2048 UitsSignature_AlgorithmType = 1
	UitsSignature_DSA2048 UitsSignature_AlgorithmType = 2
)

var UitsSignature_AlgorithmType_name = map[int32]string{
	1: "RSA2048",
	2: "DSA2048",
}
var UitsSignature_AlgorithmType_value = map[string]int32{
	"RSA2048": 1,
	"DSA2048": 2,
}

func (x UitsSignature_AlgorithmType) Enum() *UitsSignature_AlgorithmType {
	p := new(UitsSignature_AlgorithmType)
	*p = x
	return p
}
func (x UitsSignature_AlgorithmType) String() string {
	return proto.EnumName(UitsSignature_AlgorithmType_name, int32(x))
}
func (x *UitsSignature_AlgorithmType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UitsSignature_AlgorithmType_value, data, "UitsSignature_AlgorithmType")
	if err != nil {
		return err
	}
	*x = UitsSignature_AlgorithmType(value)
	return nil
}

type UitsSignature_CanonicalizationType int32

const (
	UitsSignature_NONE UitsSignature_CanonicalizationType = 1
)

var UitsSignature_CanonicalizationType_name = map[int32]string{
	1: "NONE",
}
var UitsSignature_CanonicalizationType_value = map[string]int32{
	"NONE": 1,
}

func (x UitsSignature_CanonicalizationType) Enum() *UitsSignature_CanonicalizationType {
	p := new(UitsSignature_CanonicalizationType)
	*p = x
	return p
}
func (x UitsSignature_CanonicalizationType) String() string {
	return proto.EnumName(UitsSignature_CanonicalizationType_name, int32(x))
}
func (x *UitsSignature_CanonicalizationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UitsSignature_CanonicalizationType_value, data, "UitsSignature_CanonicalizationType")
	if err != nil {
		return err
	}
	*x = UitsSignature_CanonicalizationType(value)
	return nil
}

type ProductId struct {
	Type             *ProductId_Type `protobuf:"varint,1,req,name=type,enum=musicmanager.ProductId_Type" json:"type,omitempty"`
	Completed        *bool           `protobuf:"varint,2,opt,name=completed,def=0" json:"completed,omitempty"`
	Id               *string         `protobuf:"bytes,3,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ProductId) Reset()         { *m = ProductId{} }
func (m *ProductId) String() string { return proto.CompactTextString(m) }
func (*ProductId) ProtoMessage()    {}

const Default_ProductId_Completed bool = false

func (m *ProductId) GetType() ProductId_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProductId_UPC
}

func (m *ProductId) GetCompleted() bool {
	if m != nil && m.Completed != nil {
		return *m.Completed
	}
	return Default_ProductId_Completed
}

func (m *ProductId) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type AssetId struct {
	Type             *AssetId_Type `protobuf:"varint,1,req,name=type,enum=musicmanager.AssetId_Type" json:"type,omitempty"`
	Id               *string       `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *AssetId) Reset()         { *m = AssetId{} }
func (m *AssetId) String() string { return proto.CompactTextString(m) }
func (*AssetId) ProtoMessage()    {}

func (m *AssetId) GetType() AssetId_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return AssetId_ISRC
}

func (m *AssetId) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type TransactionId struct {
	Version          *string `protobuf:"bytes,1,req,name=version,def=1" json:"version,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TransactionId) Reset()         { *m = TransactionId{} }
func (m *TransactionId) String() string { return proto.CompactTextString(m) }
func (*TransactionId) ProtoMessage()    {}

const Default_TransactionId_Version string = "1"

func (m *TransactionId) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_TransactionId_Version
}

func (m *TransactionId) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type MediaId struct {
	AlgorithmType    *MediaId_AlgorithmType `protobuf:"varint,1,req,name=algorithm_type,enum=musicmanager.MediaId_AlgorithmType" json:"algorithm_type,omitempty"`
	Hash             *string                `protobuf:"bytes,2,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MediaId) Reset()         { *m = MediaId{} }
func (m *MediaId) String() string { return proto.CompactTextString(m) }
func (*MediaId) ProtoMessage()    {}

func (m *MediaId) GetAlgorithmType() MediaId_AlgorithmType {
	if m != nil && m.AlgorithmType != nil {
		return *m.AlgorithmType
	}
	return MediaId_SHA256
}

func (m *MediaId) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type UrlInfo struct {
	Type             *UrlInfo_Type `protobuf:"varint,1,req,name=type,enum=musicmanager.UrlInfo_Type" json:"type,omitempty"`
	Url              *string       `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *UrlInfo) Reset()         { *m = UrlInfo{} }
func (m *UrlInfo) String() string { return proto.CompactTextString(m) }
func (*UrlInfo) ProtoMessage()    {}

func (m *UrlInfo) GetType() UrlInfo_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return UrlInfo_WCOM
}

func (m *UrlInfo) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type CopyrightStatus struct {
	Type             *CopyrightStatus_Type `protobuf:"varint,1,req,name=type,enum=musicmanager.CopyrightStatus_Type" json:"type,omitempty"`
	Copyright        *string               `protobuf:"bytes,2,opt,name=copyright" json:"copyright,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *CopyrightStatus) Reset()         { *m = CopyrightStatus{} }
func (m *CopyrightStatus) String() string { return proto.CompactTextString(m) }
func (*CopyrightStatus) ProtoMessage()    {}

func (m *CopyrightStatus) GetType() CopyrightStatus_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CopyrightStatus_UNSPECIFIED
}

func (m *CopyrightStatus) GetCopyright() string {
	if m != nil && m.Copyright != nil {
		return *m.Copyright
	}
	return ""
}

type Extra struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Extra) Reset()         { *m = Extra{} }
func (m *Extra) String() string { return proto.CompactTextString(m) }
func (*Extra) ProtoMessage()    {}

func (m *Extra) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Extra) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type UitsMetadata struct {
	Nonce                *string                            `protobuf:"bytes,1,req,name=nonce" json:"nonce,omitempty"`
	DistributorId        *string                            `protobuf:"bytes,2,req,name=distributor_id" json:"distributor_id,omitempty"`
	TransactionDate      *string                            `protobuf:"bytes,3,req,name=transaction_date" json:"transaction_date,omitempty"`
	ProductId            *ProductId                         `protobuf:"bytes,4,req,name=product_id" json:"product_id,omitempty"`
	AssetId              *AssetId                           `protobuf:"bytes,5,req,name=asset_id" json:"asset_id,omitempty"`
	TransactionId        *TransactionId                     `protobuf:"bytes,6,req,name=transaction_id" json:"transaction_id,omitempty"`
	MediaId              *MediaId                           `protobuf:"bytes,7,req,name=media_id" json:"media_id,omitempty"`
	UrlInfo              *UrlInfo                           `protobuf:"bytes,8,opt,name=url_info" json:"url_info,omitempty"`
	ParentalAdvisoryType *UitsMetadata_ParentalAdvisoryType `protobuf:"varint,9,opt,name=parental_advisory_type,enum=musicmanager.UitsMetadata_ParentalAdvisoryType" json:"parental_advisory_type,omitempty"`
	CopyrightStatus      *CopyrightStatus                   `protobuf:"bytes,10,opt,name=copyright_status" json:"copyright_status,omitempty"`
	Extra                []*Extra                           `protobuf:"bytes,11,rep,name=extra" json:"extra,omitempty"`
	XXX_unrecognized     []byte                             `json:"-"`
}

func (m *UitsMetadata) Reset()         { *m = UitsMetadata{} }
func (m *UitsMetadata) String() string { return proto.CompactTextString(m) }
func (*UitsMetadata) ProtoMessage()    {}

func (m *UitsMetadata) GetNonce() string {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return ""
}

func (m *UitsMetadata) GetDistributorId() string {
	if m != nil && m.DistributorId != nil {
		return *m.DistributorId
	}
	return ""
}

func (m *UitsMetadata) GetTransactionDate() string {
	if m != nil && m.TransactionDate != nil {
		return *m.TransactionDate
	}
	return ""
}

func (m *UitsMetadata) GetProductId() *ProductId {
	if m != nil {
		return m.ProductId
	}
	return nil
}

func (m *UitsMetadata) GetAssetId() *AssetId {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *UitsMetadata) GetTransactionId() *TransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func (m *UitsMetadata) GetMediaId() *MediaId {
	if m != nil {
		return m.MediaId
	}
	return nil
}

func (m *UitsMetadata) GetUrlInfo() *UrlInfo {
	if m != nil {
		return m.UrlInfo
	}
	return nil
}

func (m *UitsMetadata) GetParentalAdvisoryType() UitsMetadata_ParentalAdvisoryType {
	if m != nil && m.ParentalAdvisoryType != nil {
		return *m.ParentalAdvisoryType
	}
	return UitsMetadata_UNSPECIFIED
}

func (m *UitsMetadata) GetCopyrightStatus() *CopyrightStatus {
	if m != nil {
		return m.CopyrightStatus
	}
	return nil
}

func (m *UitsMetadata) GetExtra() []*Extra {
	if m != nil {
		return m.Extra
	}
	return nil
}

type UitsSignature struct {
	AlgorithmType        *UitsSignature_AlgorithmType        `protobuf:"varint,1,req,name=algorithm_type,enum=musicmanager.UitsSignature_AlgorithmType" json:"algorithm_type,omitempty"`
	CanonicalizationType *UitsSignature_CanonicalizationType `protobuf:"varint,2,req,name=canonicalization_type,enum=musicmanager.UitsSignature_CanonicalizationType" json:"canonicalization_type,omitempty"`
	KeyId                *string                             `protobuf:"bytes,3,req,name=key_id" json:"key_id,omitempty"`
	Value                *string                             `protobuf:"bytes,4,req,name=value" json:"value,omitempty"`
	XXX_unrecognized     []byte                              `json:"-"`
}

func (m *UitsSignature) Reset()         { *m = UitsSignature{} }
func (m *UitsSignature) String() string { return proto.CompactTextString(m) }
func (*UitsSignature) ProtoMessage()    {}

func (m *UitsSignature) GetAlgorithmType() UitsSignature_AlgorithmType {
	if m != nil && m.AlgorithmType != nil {
		return *m.AlgorithmType
	}
	return UitsSignature_RSA2048
}

func (m *UitsSignature) GetCanonicalizationType() UitsSignature_CanonicalizationType {
	if m != nil && m.CanonicalizationType != nil {
		return *m.CanonicalizationType
	}
	return UitsSignature_NONE
}

func (m *UitsSignature) GetKeyId() string {
	if m != nil && m.KeyId != nil {
		return *m.KeyId
	}
	return ""
}

func (m *UitsSignature) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Uits struct {
	Metadata         *UitsMetadata  `protobuf:"bytes,1,req,name=metadata" json:"metadata,omitempty"`
	Signature        *UitsSignature `protobuf:"bytes,2,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Uits) Reset()         { *m = Uits{} }
func (m *Uits) String() string { return proto.CompactTextString(m) }
func (*Uits) ProtoMessage()    {}

func (m *Uits) GetMetadata() *UitsMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Uits) GetSignature() *UitsSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("musicmanager.ProductId_Type", ProductId_Type_name, ProductId_Type_value)
	proto.RegisterEnum("musicmanager.AssetId_Type", AssetId_Type_name, AssetId_Type_value)
	proto.RegisterEnum("musicmanager.MediaId_AlgorithmType", MediaId_AlgorithmType_name, MediaId_AlgorithmType_value)
	proto.RegisterEnum("musicmanager.UrlInfo_Type", UrlInfo_Type_name, UrlInfo_Type_value)
	proto.RegisterEnum("musicmanager.CopyrightStatus_Type", CopyrightStatus_Type_name, CopyrightStatus_Type_value)
	proto.RegisterEnum("musicmanager.UitsMetadata_ParentalAdvisoryType", UitsMetadata_ParentalAdvisoryType_name, UitsMetadata_ParentalAdvisoryType_value)
	proto.RegisterEnum("musicmanager.UitsSignature_AlgorithmType", UitsSignature_AlgorithmType_name, UitsSignature_AlgorithmType_value)
	proto.RegisterEnum("musicmanager.UitsSignature_CanonicalizationType", UitsSignature_CanonicalizationType_name, UitsSignature_CanonicalizationType_value)
}
